name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to Production"
        required: false
        default: false
        type: boolean

jobs:
  terraform:
    name: Setup Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: terraform-fmt
        uses: dflook/terraform-fmt@v1.43.0

      - name: Initialize Terraform
        run: terraform init
          -backend-config="bucket=${{ secrets.TF_VAR_bucket }}"
          -backend-config="prefix=terraform/state"

      - name: Validate Terraform
        run: terraform validate

  plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Initialize Terraform
        run: terraform init
          -backend-config="bucket=${{ secrets.TF_VAR_bucket }}"
          -backend-config="prefix=terraform/state"

      - name: Plan Terraform
        run: terraform plan

  apply-manual:
    name: Apply Terraform (Manual)
    runs-on: ubuntu-latest
    needs: plan

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Initialize Terraform
        run: terraform init
          -backend-config="bucket=${{ secrets.TF_VAR_bucket }}"
          -backend-config="prefix=terraform/state"
          
      - name: Import GCP Project to Terraform
        run: terraform import google_project.project percentsurcharge

      - name: Apply Terraform
        run: terraform apply -auto-approve

  apply-auto:
    name: Apply Terraform (Auto)
    runs-on: ubuntu-latest
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Initialize Terraform
        run: terraform init
          -backend-config="bucket=${{ secrets.TF_VAR_bucket }}"
          -backend-config="prefix=terraform/state"

      - name: Import GCP Project to Terraform
        run: terraform import google_project.project percentsurcharge

      - name: Apply Terraform
        run: terraform apply -auto-approve
